### ISSUE TITLE
README or documentation description seems to be inaccurate

### ISSUE THREAD

**Issue by kitsuyui** [staticdev/human-readable#526]
I found that some sample code in README does not work as intended.
There are cases where the module path is incorrect.
For example, if you try to use `human_readable.time_of_day`,

```python
>>> import human_readable
>>> human_readable.time_of_day
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'human_readable' has no attribute 'time_of_day'
```

You need to use `human_readable.times.time_of_day` in fact.

```python
>>> human_readable.times.time_of_day
<function time_of_day at 0x100e70220>
```
## Environment

My environment is as follows.

- `Python 3.11.1`
- `human-readable v1.3.1`
- `macOS 13.1`

It seems that the same error will occur even in other environments by looking at the source code.

## Proposal

If my bug report is correct and we want to fix this, there are two ways to fix it.

A. Fix sample code in README and documentation
B. Fix source code so that sample code in README and documentation works

I think A. is better.
If B, it may cause confusion to current users by giving breaking changes.
Also, there is a possibility of namespace collision in the future.

**Comment by staticdev** [comment]
Thanks @kitsuyui, actually the documentation is right but there is a bug as you discovered.

The problem exactly is that [`__init__`](https://github.com/staticdev/human-readable/blob/main/src/human_readable/__init__.py) on root of the lib is missing the times methods. The best way to fix is to add it there, I have seen your PR, but it is not how the lib is intended to be used.

**Comment by kitsuyui** [comment]
@staticdev 

Thank you for your response. I see. I agree that it can be solved by adding it to `__init__`.
I will prepare another new pull request.

**Comment by staticdev** [comment]
@kitsuyui should work now on 1.3.2. Thanks.
